"use strict";
const assert = require("assert");
const { project, validDate, isUpcoming } = require("../js/core/admin-event-summary");
const v1 = { schema_version: 1, event: { title: "Boda V1", type: "wedding", date: "2028-02-29" }, template: { slug: "boda-vertical" } };
const v2 = { schema_version: 2, identity: { title: "  Fiesta V2  " }, event_type: "birthday", template: { slug: "cumple-clasico" }, schedule: { date: "2027-12-20", timezone: "America/Argentina/Buenos_Aires" } };
const before = JSON.stringify([v1, v2]);
assert.strictEqual(project({ working: v1 }).title, "Boda V1");
assert.strictEqual(project({ working: v1 }).dateLabel, "29/02/2028");
assert.strictEqual(project({ working: v2, published: v1 }).title, "Fiesta V2");
assert.strictEqual(project({ working: v2, published: v1 }).type, "birthday");
assert.strictEqual(project({ working: v2, published: v1 }).template, "cumple-clasico");
assert.strictEqual(project({ working: v2 }).source, "working");
assert.strictEqual(project({ published: v1 }).source, "published");
assert.strictEqual(project({ working: { schema_version: 99 }, published: v1 }).source, "published");
assert.strictEqual(project().source, "none");
assert.strictEqual(project().title, "Sin título");
assert.strictEqual(project().type, "Tipo no disponible");
assert.strictEqual(project().dateLabel, "Fecha no disponible");
const incomplete = project({ working: { schema_version: 2, identity: { title: "Trabajo" } }, published: v1 });
assert.strictEqual(incomplete.source, "working");
assert.strictEqual(incomplete.title, "Trabajo");
assert.strictEqual(incomplete.date, null);
assert.strictEqual(incomplete.template, "Template no disponible");
assert.strictEqual(incomplete.type, "Tipo no disponible");
assert.strictEqual(project({ working: { schema_version: 1, event: { title: 123, date: "2027-02-29" } } }).date, null);
for (const date of ["2027-02-29", "2027-04-31", "2027-13-01", "bad", "20/12/2027", "2027-1-02", null]) assert.strictEqual(validDate(date), null);
assert.strictEqual(validDate("2028-02-29"), "2028-02-29");
assert.strictEqual(isUpcoming(project({ working: v2 }), new Date("2027-12-19T12:00:00Z")), true);
assert.strictEqual(isUpcoming(project({ working: v2 }), new Date("2027-12-20T12:00:00Z")), false);
// UTC is already Dec 20; Argentina is still Dec 19.
assert.strictEqual(isUpcoming(project({ working: v2 }), new Date("2027-12-20T01:00:00Z")), true);
assert.strictEqual(isUpcoming({ date: "2027-12-20", timezone: "Invalid/Zone" }), false);
assert.strictEqual(isUpcoming(project()), false);
assert.strictEqual(JSON.stringify([v1, v2]), before);
console.log("admin event summary tests passed");
